#!/usr/bin/env zsh

taps=(
  homebrew/dupes
  homebrew/versions
  caskroom/cask
  caskroom/fonts
  heroku/brew
  koekeishiya/formulae
)

packages=(
  # caskroom/cask
  brew-cask

  # heroku/brew
  heroku

  # koekeishiya/formulae
  yabai
  skhd

  # default tap
  ack
  asdf
  coreutils
  dnstop
  dos2unix
  emacs
  exiftool
  ffmpeg
  fish
  freeimage
  freetype
  fzf
  gist
  "git --with-pcre --with-brewed-curl --with-blk-sha1 --with-gettext --with-brewed-openssl --with-persistent-https"
  git-extras
  gnu-sed
  gnu-time
  gnupg
  gnutls
  gpgme
  heroku
  htop-osx
  hub
  "imagemagick --with-webp"
  ioping
  jq
  joplin
  lazygit
  libffi
  libyaml
  lynx
  md5sha1sum
  nmap
  neovim
  openssl
  phantomjs
  pigz
  pkg-config
  proctools
  psgrep
  pv
  pwgen
  "python --with-brewed-openssl"
  qt
  ranger
  readline
  reattach-to-user-namespace
  rename
  rhino
  rtmpdump
  s3cmd
  shellcheck
  sqlmap
  ssh-copy-id
  the_silver_searcher
  tmux
  tree
  ucspi-tcp # `tcpserver` et al.
  unrar
  watch
  wdiff
  webkit2png
  wget
  yarn
  youtube-dl
  zopfli
)

cask_packages=(
  # imagealpha
  # imageoptim
  # steam
  adobe-creative-cloud
  colorpicker-hex
  google-backup-and-install
  google-chrome
  iina
  iterm2
  karabiner-elements
  macs-fan-control
  showyedge
  skype
  slack
  spotify
  the-unarchiver
  totalspaces
  transmit

  # caskroom/fonts
  font-inconsolata
  font-liberation-sans
  font-open-sans
  font-source-code-pro
  font-source-sans-pro
)

function log() {
  echo $* > /dev/stderr
}

###########################################################################

log "brew update"
brew update

log "brew upgrade"
brew upgrade

log "Tapping..."
for name in $taps
do
  log "brew tap ${name}"
  brew tap $name
done

log "Installing..."
for name_and_args in $packages
do
  log "brew install ${=name_and_args}"
  brew install "${=name_and_args}"
done

for name_and_args in $cask_packages
do
  log "brew cask install ${=name_and_args}"
  brew cask install "${=name_and_args}"
done

log "Adding asdf plugins..."
asdf plugin-add ruby
asdf plugin-add erlang
asdf plugin-add elixir
asdf plugin-add postgres
asdf plugin-add redis

log "brew cleanup"
brew cleanup

log "brew cask cleanup"
brew cask cleanup

log "brew linkapps"
brew linkapps
