#!/usr/bin/env zsh
#
# # Setup
#
# Putting this here to just to help me set up new hardware. This guide could
# get outdated pretty quick though.
#
# ```sh
# $ git clone https://github.com/vinnicc/dotfiles.git ~
# ```
#
# Get Homebrew:
#
# ```sh
# $ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# ```
#
# Run:
#
# ```sh
# $ update && bootstrap
# ```
#
# Set up Vim:
#
# ```sh
# $ curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh && \
# vim +NeoBundleInstall +qall
# ```
#
# * Review `~/.aliases` for `fish`
# * Review `~/.skhdrc` for `yabai`
# * Use `ranger` instead of Finder
# * Change screenshot directory
#
#   ```sh
#   defaults write com.apple.screencapture location ~/Downloads
#   ```
#
# ## iTerm2
#
# * General > Window > Native full screen windows > Uncheck
# * General > Load preference from a custom folder or URL > Set path to Google Drive
# * General > Save changes to folder when iTerm2 quits > Check
# * Create hotkey window and activate with ⌥ + `
#
# ## Karabiner-Elements
#
# * Enable Simultaneous Vi Mode
# * Change Caps Lock to Keycode 53 (Escape)
# * Change Fn Key - Fn to Control_L
# * Change Control_L Key - Control_L to Fn
# * Set Delay Until Repeat - 200ms
# * Set Key Repeat - 23ms
#
# ## MacOS Tweaks
#
# Pick and choose https://github.com/mathiasbynens/dotfiles/blob/master/.macos

taps=(
  homebrew/cask-fonts
  heroku/brew
  koekeishiya/formulae
)

packages=(
  # default tap
  asdf
  coreutils
  emacs
  fish
  freetype
  fzf
  git
  git-extras
  gnupg
  gnutls
  imagemagick
  joplin
  lazygit
  libffi
  libyaml
  lynx
  neovim
  openssl
  pkg-config
  ranger
  readline
  reattach-to-user-namespace
  rename
  shellcheck
  ssh-copy-id
  the_silver_searcher
  tmux
  ucspi-tcp # `tcpserver` et al.
  wget
  yarn
  youtube-dl

  # heroku/brew
  heroku

  # koekeishiya/formulae
  yabai
  skhd
)

cask_packages=(
  # imagealpha
  # imageoptim
  # steam
  # showyedge
  adobe-creative-cloud
  caprine
  colorpicker-hex
  firefox
  google-backup-and-install
  google-chrome
  iina
  iterm2
  karabiner-elements
  licecap
  macs-fan-control
  postbird
  skype
  slack
  spotify
  the-unarchiver
  transmit

  # caskroom/fonts
  font-inconsolata
  font-liberation-sans
  font-open-sans
  font-source-code-pro
  font-source-sans-pro
)

function log() {
  echo $* > /dev/stderr
}

###########################################################################

log "brew update"
brew update

log "brew upgrade"
brew upgrade

log "Tapping..."
for name in $taps
do
  log "brew tap ${name}"
  brew tap $name
done

log "Installing..."
for name_and_args in $packages
do
  log "brew install ${=name_and_args}"
  brew install "${=name_and_args}"
done

for name_and_args in $cask_packages
do
  log "brew cask install ${=name_and_args}"
  brew cask install "${=name_and_args}"
done

log "Adding asdf plugins..."
asdf plugin-add ruby
asdf plugin-add erlang
asdf plugin-add elixir
asdf plugin-add postgres
asdf plugin-add redis

log "brew cleanup"
brew cleanup
